name: Run JMeter Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:   # allows manual trigger

jobs:
  jmeter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JMeter
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: jmeter-tests/JPetStoreLogin.jmx   # path to your JMX file
          outputReportsFolder: reports

      - name: Upload JMeter Results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: reports
